# 17/07/2025:
La classe Coefficient ponderator avec des perturbations calculées avec ScoreCRiterion rend les mêmes résultats que CoefficientDeltaMSP

In [1]:
%load_ext autoreload
%autoreload 2
from ScoreCriterion import *
from modality_fusion import CoefficientPonderator, ponderer_perturbations

mkdir -p failed for path /local/maouche/.cache/matplotlib: [Errno 13] Permission denied: '/local/maouche/.cache/matplotlib'
Matplotlib created a temporary cache directory at /tmp/matplotlib-v06sqpbo because there was an issue with the default path (/local/maouche/.cache/matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.


In [21]:
scores = np.array([ [1,2,3],
                    [7,3,4],
                    [5,2,8],
                    [6,4,1]
                  ])
ponderator = CoefficientDeltaMSP()
print(ponderator(scores))

[ 7.5  11.75] None
(array([[ 50.25],
       [ 69.5 ],
       [109.  ],
       [ 41.75]]), None)


In [25]:
dataset = np.array([ [1,2,3],
                    [7,3,4],
                    [5,2,8],
                    [6,4,1]
                  ])
confs_modalites = dataset[:, 1:]
score_criterion = ScoreCriterion()

perturbations_id, perturbations_ood = score_criterion.get_perturbations(scores)
print(perturbations_id, perturbations_ood)
ponderator = CoefficientPonderator()
print(ponderator(confs_modalites, perturbations_id))


[ 7.5  11.75] None
[[ 50.25]
 [ 69.5 ]
 [109.  ]
 [ 41.75]]


In [4]:
dataset = np.array([ [1,2,3],
                    [7,3,4],
                    [5,2,8],
                    [6,4,1]
                  ])

delta_msp = DeltaMSP()
scores_id, scores_ood = delta_msp(dataset)
print(scores_id, scores_ood)

[[1 2]
 [4 3]
 [3 3]
 [2 5]] None
[[-3]
 [-7]
 [-6]
 [-7]] None


ponderer_perturbations

In [ ]:
dataset = np.array([ [1,2,3],
                     [7,3,4],
                     [5,2,8],
                     [6,4,1]
                  ])
id_conf_sans = dataset[:, 1]
id_confs = dataset[:, 1]

In [ ]:

ponderer_perturbations(id_conf_sans, id_confs, ood_confs, fct_ponderation)